
steps:
- task: PowerShell@2
  displayName: 'Executing Pester Tests'
  inputs:
    pwsh: true
    filePath: '$(System.DefaultWorkingDirectory)\devops\pipelines\scripts\pester.ps1'
    arguments: '-SourcePath $(System.DefaultWorkingDirectory)\src\ -Publish -ResultsPath $(System.DefaultWorkingDirectory)\publish'

- task: PublishCodeCoverageResults@2
  displayName: 'Publish results'
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)\publish\codecoverage.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)\src\powershell\'
