
steps:
- task: PowerShell@2
  displayName: 'Executing Pester Tests'
  inputs:
    pwsh: true
    filePath: '$(System.DefaultWorkingDirectory)\devops\pipelines\scripts\pester.ps1'
    arguments: '-SourcePath $(System.DefaultWorkingDirectory)\src\ -Publish -ResultsPath $(System.DefaultWorkingDirectory)\publish'

- task: reportgenerator@5
  displayName: 'Publish code covergae results'
  inputs:
    reports: '*.xml'
    targetdir: '$(System.DefaultWorkingDirectory)\publish'
    sourcedirs: '$(System.DefaultWorkingDirectory)\src\powershell'